version: '3'

services:
    web:
        build: ./services/web
        command: python manage.py run -h 0.0.0.0
        volumes:
            - ./services/web/:/usr/src/app/
        ports:
            - 5000:5000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ctt_db_service_id
            - POSTGRES_PASSWORD=secure_ct_transit_pass
            - POSTGRES_DB=videopull
        ports:
            - "5433:5432"
volumes:
    postgres_data:
